movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.lab,name='lab'),
    path('movie/<int:movie_id>/',views.list,name='list'),
    path('add/',views.add_list,name='add_list'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallary')

    def __str__(self):
        return self.name

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .form import MovieForm
from .models import Movie


# Create your views here.
def lab(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }

    return render(request, "list.html", context)


def list(request, movie_id):
    # return HttpResponse("This is movie no %s" % movie_id)
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add_list(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/movieapp/templates/jency.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello Jency</h1>
</body>
</html>

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<link rel="icon" href="/favicon.ico" type="image/x-icon">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
<input type="text" name="desc" placeholder="Enter your movie desc"><br>
<input type="text" name="year" placeholder="Enter year"><br>
<input type="file" name="img" placeholder="Enter img"><br><br>
    <button>Submit</button>
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body style="color:red;text-align:center;">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}>
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie List
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
    body {
    text-align:center;}
    </style>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
   <h2 style="color:blue;"> Are you want to delete this movie?</h2><br>
    <button>Ok</button>
</form>

</body>
</html>

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <img src="{{movie.img.url}}" width="300" height="300">
        </div>
<div class="col-md-4">

<h4>{{movie.name}}</h4>
    <h6>{{movie.desc}}</h6>
<h6>{{movie.year}}</h6>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
</div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align:center;">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button>Submit</button>
</form>
</body>
</html>

movieproject/templates/list.html
{% extends 'base.html' %}
{% block body %}<br>
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:list' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}